<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function getCourseNames()
    {
        $names=array();
        $courses=$this->findAll();
        foreach($courses as $course)
        {
            $names[]=$course->getName();
        }
        return $names;
    }
}
