<?php

namespace Insta\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository
{
    public function getCourseNames(Teacher $teacher)
    {
        $names=array();
        $courses=$teacher->getCourses();
        foreach($courses as $course)
        {
            $names[]=$course->getName();
        }
        return $names;
    }
}
