index_location:
    path:     /
    defaults: { _controller: PlanningBundle:Location:index }

site_list:
    path:     /sites
    defaults: { _controller: PlanningBundle:Location:siteList }

room_list:
    path:     /rooms
    defaults: { _controller: PlanningBundle:Location:roomList }

site:
    path:     /site-{id}
    defaults: { _controller: PlanningBundle:Location:site }
    requirements:
        id: \d+

room:
    path:     /room-{id}
    defaults: { _controller: PlanningBundle:Location:room }
    requirements:
        id: \d+

add_site:
    path:     /site/new
    defaults: { _controller: PlanningBundle:Location:addSite }

add_room:
    path:     /room/new
    defaults: { _controller: PlanningBundle:Location:addRoom }

edit_site:
    path:     /site-{id}/edit
    defaults: { _controller: PlanningBundle:Location:editSite }
    requirements:
        id: \d+

edit_room:
    path:     /room-{id}/edit
    defaults: { _controller: PlanningBundle:Location:editRoom }
    requirements:
        id: \d+
    
delete_room:
    path:     /room-{id}/delete
    defaults: { _controller: PlanningBundle:Location:deleteRoom }
    requirements:
        id: \d+
    
delete_site:
    path:     /site-{id}/delete
    defaults: { _controller: PlanningBundle:Location:deleteSite }
    requirements:
        id: \d+