new_lesson:
    path: /lesson/new
    defaults: { _controller: PlanningBundle:Schedule:createLesson }

new_oral:
    path: /oral/new
    defaults: { _controller: PlanningBundle:Schedule:createOral }

manage_course:
    path: /course/{course}/edit
    defaults: { _controller: PlanningBundle:Schedule:manageCourse }