planning_homepage:
    path:     /
    defaults: { _controller: PlanningBundle:Public:index }

planning_month:
    path:     /planning/{month}/{year}
    defaults: { _controller: PlanningBundle:Public:planning }
    requirements:
        month: \d+
        year: \d+

show_schedule:
    path:     /schedule/{id}
    defaults: { _controller: PlanningBundle:Public:showSchedule }
    requirements:
        id: \d+